services:
  backend:
    build:
      context: ./angebotsfindung-backend
      dockerfile: Dockerfile
    container_name: bidwise-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./angebotsfindung-frontend
      dockerfile: Dockerfile
    container_name: bidwise-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
